import flet
from flet import Page
from flet_core import Container, colors, border, Text, UserControl, Column, ScrollMode


class TextArea(UserControl):
    def __init__(self, page):
        super().__init__()
        self.expand = True
        self.view = None
        self.page = page
        self.page.scroll = True

    def build(self):
        self.view = Column(
            controls=[
                Text(
                    "afasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadafasfasfasfasfsadv",
                    # selectable=True,
                )
            ],
            scroll=ScrollMode.ALWAYS,
            alignment="center",
            horizontal_alignment="center",
        )
        return self.view


def main(page: Page):
    # page.scroll = ScrollMode.AUTO
    page.add(
        Container(
            # bgcolor="#FFCC0000",
            width=500,
            height=300,
            border=border.all(10, colors.BLACK),
            # expand=True,
            content=TextArea(page)
        )
    )


flet.app(target=main, port=8550)
