# 通用间距
CONTENT_HORIZONTAL_PADDING = 50

# FeatureBar
FEATURE_BAR_MARGIN_RIGHT = 50

# 图片列表
IMG_DISPLAY_BATCH_SIZE = 20
IMG_LIST_CONTAINER_WIDTH = 5000
IMG_LIST_CONTAINER_HEIGHT = 5000
IMG_LIST_BORDER_RADIUS = 5
IMG_LIST_MARGIN_TOP = 20
IMG_LIST_PADDING_VERTICAL = 20
IMG_LIST_PADDING_HORIZONTAL = 50
IMG_THUMB_HEIGHT = 150

# SnackBar
SNACK_BAR_WIDTH = 200
SNACK_BAR_DURATION = 2000
SNACK_BAR_MARGIN_BOTTOM = 30
SNACK_BAR_MARGIN_LEFT = 1100
SNACK_BAR_MARGIN_RIGHT = 30

# 按钮
BUTTON_HEIGHT = 50
EXTRACT_BUTTON_WIDTH = 130
BUTTON_BORDER_RADIUS = 10

# 设置项
SETTING_TEXT_FIELD_HEIGHT = 40
SETTING_TEXT_FIELD_CONTENT_PADDING_LEFT = 20
SETTING_ROW_SPACING = 10
SETTING_TEXT_SIZE = 18

# 结果数量
MIN_RESULT_COUNT = 1
MAX_RESULT_COUNT = 100